:box_output:
  :padding: 34
  :terminal_width: 46
  :amount: '1) Amount: '
  :rate: '2) Rate: '
  :length: '3) Length: '
  :payment: '4) Monthly Payment: '
:error_msg:
  :not_enough_data: "Please enter more loan terms\nbefore calculating."
  :invalid_selection: "***** Invalid selection! *****"
  :invalid_data: '**** Invalid data entered!!! ****'
  :recalc: "\n**Data is incongruous. Please recalculate a loan term**"
  :rate_error: "***No rate solution available***\nPlease adjust parameters"
:format:
  :amount: '$%.2f'
  :rate: '%.3f%%'
  :length: '%.2f months'
  :payment: '$%.2f'
:input_msg:
  :amount: 'Enter the loan amount to 2 decimal places (Ex: 200.50 for $200.50).'
  :rate: 'Enter the annual percentage rate (Ex: 2.52 for 2.52%).'
  :length: 'Enter the length of the loan in whole months (Integers only).'
  :payment: 'Enter the monthly payment amount to 2 decimal places (Ex: 20 for $20.00)'
:message:
  :prompt: '>> '
  :exit: "_Thank you for using Loan Calculator!_"
:regex:
  :amount: !ruby/regexp /^\d*\.?\d{,2}$/
  :rate: !ruby/regexp /^\d*\.?\d*$/
  :length: !ruby/regexp /^\d+$/
  :payment: !ruby/regexp /^\d*\.?\d{,2}$/